# Generated by Django 5.1.1 on 2024-12-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='1.jpg', upload_to='Profile'),
        ),
    ]
